name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'

jobs:
  linux-clang:
    runs-on: ubuntu-22.04
    name: Linux Clang
    strategy:
        fail-fast: false
        matrix:
            build_type: [Debug, Release]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Linux_${{matrix.build_type}}_${{matrix.clang_version}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=clang++ .
    - name: Build
      run: cmake --build ${{github.workspace}}/Linux_${{matrix.build_type}}_${{matrix.clang_version}} -j 2
    - name: Test
      working-directory: ${{github.workspace}}/Linux_${{matrix.build_type}}_${{matrix.clang_version}}
      run: ./tests/tests
      
  msvc_cl:
    runs-on: windows-latest
    name: Visual Studio CL
    strategy:
        fail-fast: false
        matrix:
            build_type: [Debug, Release]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/VS2022_CL -G "Visual Studio 17 2022" -A x64 .
    - name: Build
      run: msbuild VS2022_CL\Project.sln /property:Configuration=${{matrix.build_type}}
    - name: Test
      working-directory: ${{github.workspace}}\VS2022_CL\tests\${{matrix.build_type}}
      run: .\tests.exe 